---
apiVersion: v1
kind: Service
metadata:
  name: alpine
spec:
  selector:
    tool: spring-petclinic
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80            
          